import type { MetadataRoute } from "next";
import { siteConfig } from "@/data/siteConfig";

/**
 * Generates the website robots.txt file.
 *
 * Allows search engines to crawl the entire website and
 * points them to the XML sitemap generated by Next.js.
 *
 * If private or admin-only sections are added in the future,
 * they can be excluded here.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
    },

    sitemap: `${siteConfig.business.website}/sitemap.xml`,
  };
}
